---
dist: xenial
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "nTZlteHjgcJaRlDUOszRMuyvqOxi0TJIHWuC6nvwTauD9dSOiOXfRsbQIyvtC+pb+HESGJjLOOg78er3KHxZFe8flCXHChzgiKj7oCvAbGfka3bccw3q3518JxnJgbaqfbJUxEths5D/0x1M91IDHduwgEFeG4J6UmLsA4jFPr5Qp+DB82VEvWs4JwEe46iPlP8pUBqems4HE9fRDnrv8ydPXEBplQvCa7Nc7Gzh2WIVYVVJ8Wd6tQIYIMlX9Soi+939L4i1eBRYv6tTUUXWPdFeSM7tUAJg8s6/bwuy+IuJMehAEjF3p9YT24dGLYMjHoJe+Ru9xvFaxJeq6aajJKIqfOmIpYYSCzYgZQq5Qme/JwfgBES+IDVb6z3M5Thhwt20eFU4H0jtXavdM3S1aHgaL1IlNedwN2vq/SD2Hpx/4IsNXSFFjo7osHBCjCW6Xfm/pZSMBe9CZP0JgovJEfnejWnbXSoUboIWDs34AKi/cTHEx0H1o4pmlIoggxZmWoUqlVBshAPAgOIhBNeqtd8VIwe9s4tZ47qnei/hkDQq+c+KrYt45WktZjAiMJEzpZ1M0x5XqE97J3kjHIA+ZickQx2FqLeoHG65wSMEJLaG9UbBRuS4dfoaBJnDcWC5yt3rPk20qZrVb/5MAV6fxoUP7K/s2AtOS7L3OHj7vFI="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
